"""create problems and attempts

Revision ID: b956df9fbdf5
Revises: 
Create Date: 2026-10-03 21:17:29.469895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b956df9fbdf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('pattern', sa.Enum('arrays_hashing', 'two_pointers', 'sliding_window', 'stack', 'binary_search', 'linked_list', 'trees', 'tries', 'heap', 'backtracking', 'graphs', 'advanced_graphs', 'dp_1d', 'dp_2d', 'greedy', 'intervals', 'math_geometry', 'bit_manipulation', name='pattern', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.CheckConstraint('number > 0', name=op.f('ck_problems_number_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems')),
    sa.UniqueConstraint('number', name=op.f('uq_problems_number'))
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('attempted_on', sa.Date(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('used_hint', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('confidence BETWEEN 1 AND 5', name=op.f('ck_attempts_confidence_range')),
    sa.CheckConstraint('duration_seconds >= 0', name=op.f('ck_attempts_duration_nonnegative')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_attempts_problem_id_problems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index(op.f('ix_attempts_problem_id'), 'attempts', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempts_problem_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('problems')
    # ### end Alembic commands ###
